### ISSUE TITLE
Buckling Effect

### ISSUE THREAD

**Issue by huey0528** [jason-huang03/SPH_Project#1]
Hi Jason

Thank you for your great jobs. May I know how to do the Buckling Effect simulation? I did not found the scenes json file for that one. 

Best Wishes

**Comment by jason-huang03** [comment]
Thanks for your issue! I am deeply ashamed that the implementation of emitter is quite awful. The buckling effect simulation is supposed to be `final_scene3.json`, and the coiling effect is `final_scene4.json`. As you can see, simulating those two effects requires the implementation of emitter. Roughly speaking, I realize this by setting a 'gravity upper bound',  as is shown in the `gravitationUpper` entry in the config file. Above this threshold, gravity is disabled, and the fluid particle's speed is not allowed to change. You can find the detail in `./SPH/fluid_solvers/base_solver.py`. With this trick we can have the effect of emitter, but it is definitely not a graceful solution.

**Comment by huey0528** [comment]
Thank you for your reply~ 
I found the Buckling Effect simulation in the final_scene3.json, and I closed that issue. ^_^

**Comment by jason-huang03** [comment]
Thanks for your issue! I am deeply ashamed that the implementation of the
emitter is quite awful. The buckling effect simulation is supposed to be
scene3.json, and the coiling effect is scene4.json. As you can see,
simulating those two effects requires the implementation of an emitter.
Roughly speaking, I realize this by setting a 'gravity upper bound', as is
shown in the gravitationUpper entry in the config file. Above this
threshold, gravity is disabled, and the fluid particle's speed is not
allowed to change. You can find the detail in
./SPH/fluid_solvers/base_solver.py. With this trick we can have the effect
of emitter, but it is definitely not a graceful solution.

**Comment by jason-huang03** [comment]
Glad to hear it!
