### ISSUE TITLE
.blend scene file

### ISSUE THREAD

**Issue by ueoo** [jason-huang03/SPH_Project#2]
Hi, thanks for the amazing framework.
Could you please provide the `.blend` scene files used for rendering the scenes in the README?

**Comment by jason-huang03** [comment]
Sure！how to send it to you?

**Comment by ueoo** [comment]
Great, thanks!
How about put them in online drives such as Google Drive, Dropbox, or even Tsinghua disk?
If the files are not too large, they can be put into this repo.

**Comment by ueoo** [comment]
Hi @jason-huang03 , any news about the `.blend` scene files?
Thanks.

**Comment by jason-huang03** [comment]
I shall upload today!

**Comment by ueoo** [comment]
thanks

**Comment by jason-huang03** [comment]
https://cloud.tsinghua.edu.cn/d/263018c65ac14960a910/ sorry for being late

**Comment by jason-huang03** [comment]
If you want the high resolution image/video of the rendered scene, feel
free to ask!

**Comment by ueoo** [comment]
Thanks
