### ISSUE TITLE
compute pressure force error?

### ISSUE THREAD

**Issue by Bryan-Wong919** [jason-huang03/SPH_Project#3]
Hi, thanks for your greak work, it really inspires me a lot . However, i'm wondering whether it is correct to compute two pressure force while computing pressure acceleration between two fluid particles.
![image](https://github.com/jason-huang03/SPH_Project/assets/79688841/0c6d1485-55ed-4b7a-abe2-c17185222c54)
In "Versatile Rigid-Fluid Coupling for Incompressible SPH", it only use one pressure force.
In "Versatile Rigid-Fluid Coupling for Incompressible SPH":
![image](https://github.com/jason-huang03/SPH_Project/assets/79688841/4b8a46a5-045b-417d-929d-111329ff710d)
I'm wondering if you take interaction force into consideration. But i think that it should not be correct?
Looking forward to your reply!

**Comment by jason-huang03** [comment]
Thank you for your comment! Here I follow the equation in [this tutorial](https://animation.rwth-aachen.de/media/papers/64/2019-EG-SPH_Tutorial.pdf), and it estimates the gradient using this formula:
![image](https://github.com/jason-huang03/SPH_Project/assets/110245937/cab74642-a8b8-47c6-846f-eb78cd3f85d6)

I believe that both implementation will give reasonable visual result.

**Comment by Bryan-Wong919** [comment]
> Thank you for your comment! Here I follow the equation in [this tutorial](https://animation.rwth-aachen.de/media/papers/64/2019-EG-SPH_Tutorial.pdf), and it estimates the gradient using this formula: ![image](https://private-user-images.githubusercontent.com/110245937/341712395-cab74642-a8b8-47c6-846f-eb78cd3f85d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Njg0MjYsIm5iZiI6MTcxODk2ODEyNiwicGF0aCI6Ii8xMTAyNDU5MzcvMzQxNzEyMzk1LWNhYjc0NjQyLWE4YjgtNDdjNi04NDZmLWViNzhjZDNmODVkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxMTA4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2MyMzYzZjViZjQ1OWM2Y2Y1NTlhYzY2ZmZmZjgzMjM0MjM3NGUxYTgxZjYxNzhmYzY5YmI4YmY1YjhhZjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ccH-_kSSytuM7w_cb-yDYnN0AD697eMxjWUFEE22osg)
> 
> I believe that both implementation will give reasonable visual result.

Thank you so much for your quick reply ! It really helps me a lot !
